apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
      - name: feed-api
        image: 29061999/udagram-api-feed:v1
        resources:
          requests:
            cpu: "500m"    # Request 500 millicores (0.5 vCPU)
            memory: "256Mi"  # Request 256 MiB memory
          limits:
            cpu: "1000m"   # Limit to 1 vCPU
            memory: "512Mi" # Limit to 512 MiB
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws/credentials
          subPath: credentials
        env:
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_PROFILE
      
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-secret 
