apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-config
data:
  app.config.json: |
    {
        "backendHost":"http://ad225a45de7884affa0ed1399240b72b-1399016168.us-east-1.elb.amazonaws.com:8080/api/v0"
    }
